services:
  - type: web
    name: strapi-blog-cms
    runtime: node
    plan: free
    buildCommand: rm -rf node_modules && npm run render:build
    startCommand: npm run start
    healthCheckPath: /_health
    envVars:
      - key: NODE_VERSION
        value: "22"
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: SERVER_PROXY
        value: "true"
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_SSL
        value: "true"
      - key: DATABASE_SSL_REJECT_UNAUTHORIZED
        value: "false"
      - key: PUBLIC_URL
        sync: false
      - key: STRAPI_ADMIN_BACKEND_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: APP_KEYS
        sync: false
      - key: API_TOKEN_SALT
        sync: false
      - key: ADMIN_JWT_SECRET
        sync: false
      - key: TRANSFER_TOKEN_SALT
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
      - key: CLOUDINARY_FOLDER
        value: strapi-blog-cms
      - key: CORS_ORIGIN
        sync: false
